### ISSUE TITLE
Levantar as dependências entre includes - Amosphere

### ISSUE THREAD

**Issue by luflarois** [monanadmin/monan#143]
Levantar as dependências entre os arquivos fontes e seus procedures e os includes que eles usam.

**Comment by ebiduardo** [comment]
boa tarde colegas.
Levantar quer dizer: identificar?

**Comment by deniseiras** [comment]
Boa tarde. Sim Eduardo. Acredito que seja, por exemplo:
module atm_core_interface 
...
#include "core_variables.inc"

Esse arquivo core_variables.inc é uma dependência do módulo atm_core_interface.
Por sua vez, core_variabels.inc pode ter outros #include dentro dele.

Estou usando um programa que já gera as dependências entre módulos, mas inda não prevê esse tipo de include, somente "use module": https://github.com/deniseiras/fortranMakeUtils.git
Veja: #144 , #139 (começando agora, é uma melhoria na 144 pra prever orientação a objetos no Fortran).

O Luiz Flávio também trabalhou em um programa em Fortran que faz coisas parecidas.

**Comment by ebiduardo** [comment]
boa tarde Denis.
desculpoe a hora.
antes que a sexta feira acabe.
estou iniciando o uso do programa e tive erros.
![image](https://user-images.githubusercontent.com/14222114/202789493-20282cba-10f1-44f6-b198-65cabbd64a65.png)

bidu@DESKTOP-JTGFB7H:fortranMakeUtils-master$ python fortranMakeUtils.py fortranFiles outB 14000
Using python 3.8
Searching for modules and routines ( subroutines, functions, interfaces ) ...
Searching for uses of modules and callers of routines ...
creating callee tree ...
Traceback (most recent call last):
  File "/mnt/c/Users/bidu/OneDrive/aLncc/monan/fortranMakeUtils-master/fortranUtils.py", line 300, in createCalleeTreeIntenal
    createCalleeTreeIntenal(eachCaller, allCalles, calleeLevel, max_level)
  File "/mnt/c/Users/bidu/OneDrive/aLncc/monan/fortranMakeUtils-master/fortranUtils.py", line 300, in createCalleeTreeIntenal
    createCalleeTreeIntenal(eachCaller, allCalles, calleeLevel, max_level)
  File "/mnt/c/Users/bidu/OneDrive/aLncc/monan/fortranMakeUtils-master/fortranUtils.py", line 300, in createCalleeTreeIntenal
    createCalleeTreeIntenal(eachCaller, allCalles, calleeLevel, max_level)
  [Previous line repeated 995 more times]
  File "/mnt/c/Users/bidu/OneDrive/aLncc/monan/fortranMakeUtils-master/fortranUtils.py", line 297, in createCalleeTreeIntenal
    if eachCallee.method == eachCaller.method:
  File "/mnt/c/Users/bidu/OneDrive/aLncc/monan/fortranMakeUtils-master/fortranUtils.py", line 45, in __eq__
    if isinstance(other, Method):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by ebiduardo** [comment]
experimentei usar o diretorio que fontes que esta no proprio conjunto:fortranFiles

**Comment by deniseiras** [comment]
Oi Bidu.
Tem uma linha no código que gera esse erro. Algo como
setmaxrecursion(total+100). A ideia era que não ficasse em loop infinito em
casos de recursividade de chamadas infinita. Esse total é sua variavel que
passou na linha de comando. Ou vc comenta essa linha ou aumenta o valor do
100. Pode ser que de stackoverflow.
Eu corrigi um bug que limita a recursividade de metodos recursivos, mas ela
ainda acontece em outros casos.


Em sex., 18 de nov. de 2022 16:47, eduardo lucio mendes garcia <
***@***.***> escreveu:

**Comment by ebiduardo** [comment]
entendi. obrigado.
tem chance de eu olhar o codigo e sugerir alguma modificação.
me interesso apesar da dificuldade que isso representa.


eu experimentei valores maiores também, sem sucesso.
quando ocorre o erro não produz resultado intermediário?

Em sex., 18 de nov. de 2022 às 19:25, Denis Eiras ***@***.***>
escreveu:

**Comment by ebiduardo** [comment]
entendi. obrigado.

tem chance de eu olhar o codigo e sugerir alguma modificação.
me interesso, apesar da dificuldade que isso representa.


eu experimentei valores maiores também, sem sucesso.
quando ocorre o erro não produz resultado intermediário?

**Comment by ebiduardo** [comment]
voce tem casos de bom funcionamento para voce disponibilizar?
1. um dos modulos
2. outro de função, parametros 4 e 5
3.

**Comment by deniseiras** [comment]
Olá Bidu. bom dia. 
Fiz o mesmo teste seu e não ocorreu o erro. Mas de qq forma, estou alterando o código para simplificá-lo e gerar uma saída mais simples. Te aviso hoje ainda.

Para testar sem erros por enquanto, vc pode apagar os arquivos rio.f90 var_tables.f90 cptecBramsIoFacade.f90 cptecBramsIo.f90. Ou testar em outros códigos que não façam recursão.

**Comment by ebiduardo** [comment]
bom dia
vou fazer o que voce esta sugerindo
obrigado


Em seg., 21 de nov. de 2022 às 09:59, Denis Eiras ***@***.***>
escreveu:

**Comment by ebiduardo** [comment]
acho que a causa dos erros era um diretorio: fold1 dentro da pasta
fortranFiles.
eu não me lembro de te-lo criado conscientemente.

Em seg., 21 de nov. de 2022 às 09:59, Denis Eiras ***@***.***>
escreveu:

**Comment by ebiduardo** [comment]
não tome isso como reclamações.


Em seg., 21 de nov. de 2022 às 10:30, Denis Eiras ***@***.***>
escreveu:

**Comment by deniseiras** [comment]
Claro que não. Essas melhorias vão ser úteis para essas e futuras
atividades.

*Denis Eiras*





Em seg., 21 de nov. de 2022 às 10:33, eduardo lucio mendes garcia <
***@***.***> escreveu:

**Comment by ebiduardo** [comment]
oi denis.
o diretorio fortranfile contem um grupo de arquivo para testes.
me pareceu que os arquivos não compilam.
compilar não é importantre?

**Comment by robertopsouto** [comment]
@luflarois , fiz modificações no código `gera.F90` para ler os arquivos terminados em `_include.txt` na pasta `monan/data/`, gerando como resultado este arquivo `.dot`:
[core_atmosphere_include.dot.txt](https://github.com/monanadmin/monan/files/10099177/core_atmosphere_include.dot.txt)

Foi gerada então figura usando comando `dot` do graphviz:
![core_atmosphere_include](https://user-images.githubusercontent.com/18168063/204159140-45d3f78e-dc86-4a6e-b962-2509254210c7.svg)
![core_atmosphere_include](https://user-images.githubusercontent.com/18168063/204159161-de794b34-880b-4df8-ad88-14ba8973b83a.png)

O grafo está com muitas arestas e nós sobrepostos. Talvez com o `dot` se consiga fazer com que as arestas e nós fiquem melhor dispostos, sem tanta sobreposição.
